#+STARTUP: latexpreview
* Experiment 1:
Test how the number of sensors affects the inference by setting up sources and sensors
in a 2D space.
*Outputs*: results/exp1
*Report*: Experiment discarded: There is an error in code.The value for K (connectivity scaling) 
should be -ve. But +ve value was used. Need to rerun the experiment with -ve value of K.
* Experiment 2:
Date: /02-02-2018/
Generate a propagation pattern in a network with 5 nodes where node 2 is EZ and node 5 is PZ
*Outputs*: results/exp3
*Report*: I was using +ve values for K (connecitivity scaling) which should have been -ve. Using
-ve values for K generated the required propagation patterns.
* Experiment 3:
/Date: 02-02-2018/
Fit a network of 2D epileptors with 5 nodes using source signals (/x/ and /z/) as modelled data
*Outputs*: results/exp2
*Report*: Out of 8 chains 5 have converged. Of these 5 chains 4 have inferred the x0 accurately 
even distinguishing between EZ and PZ. However, 1 chain inferred wrongly an extra node as EZ 
apart from the actual EZ and PZ.

* Experiment 4:
Date: /02-02-2018/
Rerun Exp.1 with the correct values for K (see Exp.2)
*Outputs*: results/exp4
*Report*: $\hat r$ did not decrease as the #of sensors used for inference are increased.

* Experiment 5:
/Date: 05-02-2018/
Continuing from Exp.3, Check if increasing sigma would allow all chains to converge.
*Outputs*: results/exp5
*Report*: All the chains have converged with higher sigma. However, one chains still inferred
a different mode than the true one.

* Experimet 6:
/Date: 06-02-2018/
Now that Exp.3 and 5 showed promising results for inference at source level. Try fitting 
at sensor level with a simple source sensor geometry like in Exp. 1 (or 4) inferring only x0
*Outputs*: results/exp6
*Report*: Different chains have converged to different modes, only one chain explored the mode
of interest. 
*Question*: 
Why isn't each chain exploring all the modes? 
None of the chains are reporting divergence, for most of the chains rhat is ~1 and tree depth
is below the max. depth, So it is not the case that sampler is stuck in some complicated
curvature of posterior.
** Experimet 6.1:
Date: 15-02-18
In Exp. 6 $x_0$s are not constrained with any lower or upper bound. Check if constraining
them to the interval [-3, 0] would be improve the inference.

* Experiment 7:
/Date:13-02-2018/
Infer the source signals from the seeg data without even using the dynamical model.
*Outputs*: results/exp7
*Report*: 
